package nu.wasis.stunden;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;

import nu.wasis.stunden.cli.StundenOptions;
import nu.wasis.stunden.config.InputPluginBundle;
import nu.wasis.stunden.config.OutputPluginBundle;
import nu.wasis.stunden.config.PluginConfig;
import nu.wasis.stunden.config.ProcessPluginBundle;
import nu.wasis.stunden.exception.InvalidConfigurationException;
import nu.wasis.stunden.model.WorkPeriod;
import nu.wasis.stunden.plugin.InputPlugin;
import nu.wasis.stunden.plugin.OutputPlugin;
import nu.wasis.stunden.plugin.PluginLoader;
import nu.wasis.stunden.plugin.ProcessPlugin;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.ParseException;
import org.apache.commons.cli.PosixParser;
import org.apache.commons.io.IOUtils;
import org.apache.log4j.Logger;

/**
 * The `main' class of stunden, containing the <code>main</code> method.
 */
public class Stunden {

    private static final Logger LOG = Logger.getLogger(Stunden.class);

    /**
     * The main method of stunden. Basically does this:
     * <ol>
     *     <li>Read configuration from the file provided via the <code>c</code>
     *         command line parameter.</li>
     *     <li>Load & run all {@link InputPlugin}s and combine the results into
     *         one {@link WorkPeriod}.</li>
     *     <li>Load all {@link ProcessPlugin}s and make them process (and
     *         probably manipulate) the {@link WorkPeriod}.</li>
     *     <li>Load all {@link OutputPlugin}s and make them output the result
     *         of steps 2 and 3.</li>
     * </ol>
     * All plugins will be run in the order in which they appear in the
     * configuration file.
     * 
     * @param args The command line args. See {@link StundenOptions} for valid
     *             values.
     * @throws ParseException the command line cannot be parsed.
     * @throws IOException the configuration file cannot be read properly.
     */
    public static void main(final String[] args) throws ParseException, IOException {
        final CommandLineParser parser = new PosixParser();
        final CommandLine cmd = parser.parse(new StundenOptions(), args);

        if (!checkCommands(cmd)) {
            return;
        }

        final InputStreamReader streamReader = new FileReader(new File(cmd.getOptionValue(StundenOptions.OPTION_CONFIG_FILE)));
        final String fileContent = IOUtils.toString(streamReader);

        WorkPeriod combinedWorkPeriod = runInputPlugins(fileContent);
        if (null == combinedWorkPeriod) {
        	LOG.error("Error running the input plugins. Quitting.");
        	return;
        }
        combinedWorkPeriod = runProcessPlugins(combinedWorkPeriod, fileContent);
        if (null == combinedWorkPeriod) {
        	LOG.error("Error running the process plugins. Quitting.");
        	return;
        }

        runOutputPlugins(fileContent, combinedWorkPeriod);
    }
    
    /**
     * Load and run all {@link InputPlugin}s.
     * 
     * @param configFileContent The content of the configuration file.
     * @return A combined {@link WorkPeriod}, containing the results of all
     *         {@link InputPlugin} runs.
     * @throws IOException failed to load one of the {@link InputPlugin}s.
     */
    private static WorkPeriod runInputPlugins(final String configFileContent) throws IOException {
    	// Load input plugins
        List<InputPluginBundle> inputPluginBundles = null;
        try {
            inputPluginBundles = new PluginLoader().readInputPlugins(configFileContent);
        } catch (final InvalidConfigurationException e) {
            LOG.error("Error loading your damn input plugins. Fix your config, I'm outta here.", e);
            return null;
        }

        // Run input plugins
        WorkPeriod combinedWorkPeriod = null;
        try {
            combinedWorkPeriod = readCombinedWorkPeriod(inputPluginBundles);
        } catch (final Exception e) {
            LOG.error("Error while reading input:", e);
            return null;
        }
        if (null == combinedWorkPeriod || combinedWorkPeriod.getDays().isEmpty()) {
            LOG.warn("No input plugin generated any data. I'm outta here.");
            return null;
        }
        return combinedWorkPeriod;
    }
    
    /**
     * Loads and runs all {@link ProcessPlugin}s.
     * 
     * @param combinedWorkPeriod The {@link WorkPeriod} generated by the
     *                           {@link InputPlugin}s. 
     * @param configFileContent The content of the configuration file.
     * @return The result of {@link ProcessPlugin} chain defined in the
     *         configuration file.
     */
    private static WorkPeriod runProcessPlugins(WorkPeriod combinedWorkPeriod, final String configFileContent) {
    	// Load process plugins
        List<ProcessPluginBundle> processPluginBundles = null;
        try {
        	processPluginBundles = new PluginLoader().readProcessPlugins(configFileContent);
        } catch (final InvalidConfigurationException e) {
            LOG.error("Error loading your damn process plugins. Fix your config, I'm outta here.", e);
            return null;
        }
        
        // Run process plugins
        for (final ProcessPluginBundle processPluginBundle : processPluginBundles) {
			final ProcessPlugin processPlugin = processPluginBundle.getProcessPlugin();
			final PluginConfig pluginConfig = processPluginBundle.getPluginConfig();
			LOG.info("Processing via `" + processPlugin.getClass().getName() + "'...");
			try {
				combinedWorkPeriod = processPlugin.process(combinedWorkPeriod, pluginConfig.getConfiguration());
			} catch (final Exception e) {
				LOG.error("Error processing via " + processPlugin.getClass().getName() + ": ", e);
				return null;
			}
			LOG.info("...done.");
		}
        return combinedWorkPeriod;
    }
    
    /**
     * Load the configured {@link OutputPlugin}s and make them output the
     * {@link WorkPeriod}.
     * 
     * @param configFileContent The content of the configuration file.
     * @param combinedWorkPeriod The {@link WorkPeriod} generated by the
     *        {@link InputPlugin}s and processed by the {@link ProcessPlugin}s.
     */
    private static void runOutputPlugins(final String configFileContent, final WorkPeriod combinedWorkPeriod) {
    	// Load output plugins
        List<OutputPluginBundle> outputPluginBundles = null;
        try {
            outputPluginBundles = new PluginLoader().readOutputPlugins(configFileContent);
        } catch (final InvalidConfigurationException e) {
            LOG.error("Error loading your damn output plugins. Fix your config, I'm outta here.", e);
            return;
        }

        // Run output plugins
        for (final OutputPluginBundle outputPluginBundle : outputPluginBundles) {
            final OutputPlugin outputPlugin = outputPluginBundle.getOutputPlugin();
            try {
                final Object pluginConfig = outputPluginBundle.getPluginConfig().getConfiguration();
                LOG.info("Outputting via `" + outputPlugin.getClass().getName() + "'...");
                outputPlugin.output(combinedWorkPeriod, pluginConfig);
                LOG.info("... done.");
            } catch (final Exception e) {
                LOG.warn("Output plugin `" + outputPlugin.getClass().getName() + "' failed:", e);
            }
        }
    }

    /**
     * Runs the {@link InputPlugin}s from the provided
     * {@link InputPluginBundle}s and combines the results.
     * 
     * @param inputPluginBundles A {@link List} of preconfigured
     *        {@link InputPluginBundle}s
     * @return The {@link WorkPeriod} combined from the outputs of the
     *         {@link InputPlugin}s.
     */
    private static WorkPeriod readCombinedWorkPeriod(final List<InputPluginBundle> inputPluginBundles) {
        WorkPeriod combinedWorkPeriod = null;
        for (final InputPluginBundle inputPluginBundle : inputPluginBundles) {
            final InputPlugin inputPlugin = inputPluginBundle.getInputPlugin();
            final Object pluginConfig = inputPluginBundle.getPluginConfig().getConfiguration();
            LOG.info("Reading via `" + inputPlugin.getClass().getName() + "'...");
            final WorkPeriod workPeriod = inputPlugin.read(pluginConfig);
            if (null == combinedWorkPeriod) {
                combinedWorkPeriod = workPeriod;
            } else {
                combinedWorkPeriod.addAll(workPeriod);
            }
            LOG.info("... done.");
        }
        return combinedWorkPeriod;
    }

    /**
     * Check the command line arguments.
     * @param cmd The {@link CommandLine} generated from <code>args</code>.
     * @return <code>true</code>, if cmd contains the
     *         {@link StundenOptions#OPTION_CONFIG_FILE} param. Else
     *         <code>false</code>.
     */
    private static boolean checkCommands(final CommandLine cmd) {
        if (!cmd.hasOption(StundenOptions.OPTION_CONFIG_FILE)) {
            LOG.error("Option `" + StundenOptions.OPTION_CONFIG_FILE + "' is not optional.");
            return false;
        }

        return true;
    }
}
